name: Send GeekNews

on:
  schedule:
    - cron: '0 1 * * 1-5'
    - cron: '0 6 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install packages
        run: pip install -r requirements.txt

      - name: run script
        env:
          KAKAOWORK_WEBHOOK: ${{ secrets.KAKAOWORK_WEBHOOK }}
        run: python send_news.py
